Test Speaker: F01
Log File Path: output/logs/torgo_tiny_finetune_F01/F01_train_20240602_025454.log

Splitting the dataset into training / validation / test sets...
Unique speakers found in the dataset:
['F01' 'F03' 'F04' 'FC01' 'FC02' 'FC03' 'M01' 'M02' 'M03' 'M04' 'M05'
 'MC01' 'MC02' 'MC03' 'MC04']

After removal of repeated prompts, the number of data in each dataset is:
Train:       9749/15091 (64%)
Validation:  483/1075 (44%)
Test:        126/228 (55%)

After filter, the number of data in each dataset is:
Train:       9638/15091 (63%)
Validation:  460/1075 (42%)
Test:        115/228 (50%)

/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)
/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
No checkpoint found in the repository. Training from scratch.
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "/work/van-speech-nlp/jindaznb/jslpnb/mllm_expriments/Whispering-LLaMA/data_preparation/2_finetune_whisper_on_torgo.py", line 546, in <module>
    trainer.train()
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/transformers/trainer.py", line 1546, in train
    return inner_training_loop(
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/transformers/trainer.py", line 1780, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/transformers/trainer_callback.py", line 362, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/transformers/trainer_callback.py", line 406, in call_event
    result = getattr(callback, event)(
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/transformers/integrations.py", line 760, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/transformers/integrations.py", line 734, in setup
    self._wandb.init(
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1163, in init
    wi.setup(kwargs)
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 300, in setup
    wandb_login._login(
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 334, in _login
    wlogin.prompt_api_key()
  File "/work/van-speech-nlp/jindaznb/mmenv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 263, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
